name: Preview Deploy

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - dev
  push:
    branches:
      - test/fe/#9

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel Preview
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--force'
          github-token: ${{ secrets.AUTO_ACTIONS }}
          github-comment: ${{ github.event_name == 'pull_request' }}

      - name: Output Preview URL for Push Events
        if: github.event_name == 'push'
        run: |
          echo "🍏 Preview 배포: https://${{ steps.deploy.outputs.preview-url }}"
          echo "Since this is a push event, PR comment was skipped."
