name: Preview Deploy

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - dev

permissions:
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.event.repository.full_name

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel Preview
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--preview --force'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: true

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = process.env.VERCEL_URL;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 프리뷰 배포가 완료되었습니다!\n\n🔗 프리뷰 URL: https://${previewUrl}`
            });
        env:
          VERCEL_URL: ${{ steps.deploy.outputs.preview-url }}
